/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package videopuzzle;

/**
 *
 * @author homor
 */
public class rendirse extends javax.swing.JFrame {

    /**
     * Creates new form rendirse
     */
    public rendirse() {
        initComponents();
        setSize(600, 300);
        this.setLocationRelativeTo(null);
    }
    ventanaPuzzle ventana = new ventanaPuzzle();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonNo = new javax.swing.JButton();
        botonSi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonNo.setBackground(new java.awt.Color(255, 0, 0));
        botonNo.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        botonNo.setText("NO");
        botonNo.setToolTipText("Vamos tu puedes!!!");
        botonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNoActionPerformed(evt);
            }
        });
        getContentPane().add(botonNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 157, 138, 73));

        botonSi.setBackground(new java.awt.Color(0, 255, 0));
        botonSi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonSi.setText("SI");
        botonSi.setToolTipText("Que mal amigo");
        botonSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiActionPerformed(evt);
            }
        });
        getContentPane().add(botonSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 157, 138, 73));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¿Seguro que quieres rendirte?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 20, -1, 91));

        jLabel2.setBackground(new java.awt.Color(255, 255, 51));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_botonNoActionPerformed

    private void botonSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiActionPerformed
        // TODO add your handling code here:
        ventana.tiempo.stop();
        botonNo.setVisible(false);
        botonSi.setVisible(false);
        jLabel1.setText("Perdiste el Juego");
        
    }//GEN-LAST:event_botonSiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonNo;
    private javax.swing.JButton botonSi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
